define(['jquery'], function($){
	// 所有对话框事件
	$(document).on('click','.page-setting,.icon-file-text',function(){
		$('#page-setting-dialog').dialog("open");
	});
	$(document).on('click','.form-setting',function(){
		$('#form-setting-dialog').dialog("open");
	});
	$(document).on('click','.icon-table2,.formtab',function(){
		$('#form-dialog').dialog("open");
	});
	$(document).on('click','.exception',function(){
		$('#exception-dialog').dialog("open");
	});
	$(document).on('click','.newguide',function(){
		$('#guide-dialog').dialog("open");
	});
	$(document).on('click','#lineAttrSubmit',function(){
		$('#zhixianshuxing').dialog('close');
	});
	$(document).on('click','#exceptionSubmit',function(){
		$('#exception-dialog').dialog('close');
	});
	$(document).on('click','#formSetSubmit',function(){
		$('#form-setting-dialog').dialog('close');
	});
	$(document).on('click','#formSubmit',function(){
		$('#form-dialog').dialog('close');
	});
	$(document).on('click','#initSubmit',function(){
		$('#page-initial').dialog('close');
	});
	$(document).on('click','#pageSetSubmit',function(){
		$('#page-setting-dialog').dialog('close');
	});
	$(document).on('click','#rectSubmit,.rectAttrSubmit',function(){
		$('#juxingshuxing').dialog('close');
	});
	$(document).on('click','#picSubmit',function(){
		$('#tupianshuxing').dialog('close');
	});
	$(document).on('click','.textSubmit,.textAttrSubmit',function(){
		$('#wenbenshuxing').dialog('close');
	});
	$(document).on('click','#lineSubmit',function(){
		$('#zhixianshuxing').dialog('close');
	});
	$(document).on('click','.barSubmit,.codeAttrSubmit',function(){
		$('#tiaomashuxing').dialog('close');
	});
	$(document).on('click','#barGuideSubmit',function(){
		$('#tiaomaxiangdao').dialog('close');
	});
	$(document).on('click','#textGuideSubmit',function(){
		$('#wenbenxiangdao').dialog('close');
	});
});